### PR TITLE
Only call consume once when using BufIter

### PR DESCRIPTION
**Pull request by kamalmarhubi**
This moves the call to `consume` into a `Drop` impl on `BufIter`,
reducing the number of conditionals in the inner loop when iterating.

Not benchmarked.

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
maybe hold off merging as I'd like to add a note about the use of unsafe.

**Comment by tokenrove** [comment]
Thanks!  I'm planning to add some benchmarks.

My first pass at this I was concerned that this interfered with how I've used this code in the past (reading and writing interleaved while consuming small amounts) but I don't think that code used the iterator interface at all, so it should be fine.  The tests that take part of the iterator are part of the specific desired behavior, by the way, so it would be better to create additional tests that consume the iterator completely.  Actually, I should go back and write some quickcheck tests.

BTW, is there also a safety argument to be made for this change?  (probably something interleaving iterator access with direct consume calls?  I need to think about this some more)  If so, I would want to add that rationale to the commit message that introduces the change, and a test that demonstrates the unsafety of the previous behavior.

**Comment by kamalmarhubi** [comment]
> My first pass at this I was concerned that this interfered with how I've used this code in the past (reading and writing interleaved while consuming small amounts) but I don't think that code used the iterator interface at all, so it should be fine.

Do you have some example uses? I am actually not sure how it's used. I just saw this `buf.consume(1)` thing going on and it stood as bad.

**Comment by tokenrove** [comment]
I will look at putting up a real-world example (why I implemented this, other than making sure it could be done in Rust), adding some trivial benchmarks, and adding a few property tests (probably in the eqc state machine style), over the next couple of days, if you don't mind waiting.  Feel free to work more on these PRs or open new ones, though, they're already clear improvements over what was there before.

**Pull request closed without merging**
